#!/bin/sh
# Description: Open scrollback URLs using dmenu
# Dependencies: dmenu
# Shell: POSIX compliant
set -eu

regex="(http(s)?://|www\.)[^] \)<\"\']+"
urls=$(grep -oE "$regex" | sort -u)
[ -z "$urls" ] && exit
url=$(echo "$urls" | dmenu -l 10 -w "$WINDOWID")
[ -z "$url" ] && exit
${BROWSER:-firefox} "$url" &
